title: Alec Slim
logo: /assets/img/photo_of_me.png
description: Passionate, creative, and innovative student within The University of Southern California pursuing a Masters Degree in Applied Data Science with an expected graduation date of My 2028.
#show_downloads: true
theme: jekyll-theme-minimal
