title: Alec Slim
logo: /assets/img/photo_of_me.png
description: Passionate, creative, and innovative student within the University of California San Diego pursuing a degree in Cognitive Science with a specialization in Machine Learning and Neural Computation and expecting to graduate June 2025
#show_downloads: true
theme: jekyll-theme-minimal
